;
; global custom
;
[custom]
; lib_deps =
;   https://github.com/hatlabs/ESPAsyncHTTPClient
build_flags =
  ; -D OPENKNX_LOOPTIME_WARNING=25
  ; add OPENKNX_WATCHDOG normal only in releases and not here
  -D OPENKNX_WATCHDOG
  -D KNX_ACTIVITYCALLBACK
  -D OPENKNX_LOOPTIME_WARNING=2000
  -I lib/OGM-HardwareConfig/include/
  -D USE_TP_RX_QUEUE
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0
  ; -D OPENKNX_FREERTOS
  ; -D ARDUINO_LOOP1_STACK_SIZE=4096

[custom_develop]
extends = custom
build_flags =
  ${custom.build_flags}
  -D OPENKNX_HEARTBEAT
  ; -D OPENKNX_DEBUGGER
  ; -D OPENKNX_RUNTIME_STAT
  ; -D OPENKNX_RUNTIME_STAT_BUCKETN=7
  ; "-D OPENKNX_RUNTIME_STAT_BUCKETS=100, 200, 500, 1000, 2000, 5000"
  ; -D OPENKNX_HEARTBEAT_PRIO
  ; -D DEBUG_LOOP_TIME=10 ; will print a info when a loop took more than x ms.
  ; -D LOGIC_TRACE
  ; ; to see trace logs, they must match one of the 5 filters (TRACE_LOG1 .. TRACE_LOG2)
  ; "-D OPENKNX_TRACE1=Flash"
  ; "-D OPENKNX_TRACE1=VirtualButton.*"
  ; "-D OPENKNX_TRACE2=LED.*"
  ; "-D OPENKNX_TRACE5=Watchdog"
  ; -D OPENKNX_RTT
  ; -D BUFFER_SIZE_UP=10240
  ; "-D OPENKNX_TRACE3=modbusChannel<1>"
  ; "-D OPENKNX_TRACE4=modbusChannel<[3-5]>"

[custom_releases]
extends = custom
build_flags =
  ${custom.build_flags}

; RP2040
[RP2040_custom]
extends = RP2040, custom
build_flags =
  ; -D OPENKNX_RUNTIME_STAT
  -D modbus_FLASH_OFFSET=0xF2000
  -D modbus_FLASH_SIZE=0x1000
  -D SERIAL_DEBUG=Serial
  -D USE_KNX_DMA_UART=0
  -D USE_KNX_DMA_IRQ=0
  ; -D DEBUG_TP_FRAMES
  ; -D FORCE_ACK
  ; "-D OPENKNX_TRACE1=Button.*"

[develop_RP2040_BASE]
extends = RP2040_develop, RP2040_custom, custom_develop, RP2040_UPLOAD_USB
build_flags =
  ${RP2040_develop.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_develop.build_flags}

[env:develop_RP2040_TP]
extends = develop_RP2040_BASE, RP2040_EXCHANGE_2MB
build_flags =
  ${develop_RP2040_BASE.build_flags}
  ${RP2040_EXCHANGE_2MB.build_flags}
  ${KNX_TP.build_flags}
  ;-D DEVICE_SMARTMF_MODBUS_RTU_3BE
  -D DEVICE_SMARTMF_1TE_MODBUS
  ;-D DEVICE_SMARTMF_MODBUS_AUSSEN
; build_unflags =
;   -D USE_TP_RX_QUEUE


[env:develop_RP2040_TP_DUALCORE]
extends = env:develop_RP2040_TP
build_flags =
  ${env:develop_RP2040_TP.build_flags}
  -D OPENKNX_DUALCORE

; upload_protocol = espota
; upload_port = 192.168.13.33

[env:develop_RP2040_TP_JLINK]
extends = env:develop_RP2040_TP, UPLOAD_JLINK

[env:develop_RP2040_TP_DUALCORE_JLINK]
extends = env:develop_RP2040_TP_DUALCORE, UPLOAD_JLINK

[env:release_RP2040_TP_DEVICE_SMARTMF_MODBUS_RTU_3BE]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB, UPLOAD_JLINK
build_flags =
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  ${KNX_TP.build_flags}
  -D DEVICE_SMARTMF_MODBUS_RTU_3BE


[env:release_RP2040_TP_DEVICE_SMARTMF_1TE_MODBUS]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB, UPLOAD_JLINK
build_flags =
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  ${KNX_TP.build_flags}
  -D DEVICE_SMARTMF_1TE_MODBUS



[env:release_RP2040_TP_DEVICE_SMARTMF_MODBUS_AUSSEN]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB, UPLOAD_JLINK
build_flags =
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  ${KNX_TP.build_flags}
  -D DEVICE_SMARTMF_MODBUS_AUSSEN