#include <OpenKNX.h>
#include <Logic.h>
#include "HardwareDevices.h"
//#include "hardware.h"
#include "Device.h"
#include "Wire.h"

void appSetup();
void appLoop();

void setup()
{
#ifdef ARDUINO_ARCH_RP2040
  #ifdef BOARD_MASIFI_MODBUS_BREAKOUT
    Serial2.setRX(KNX_UART_RX_PIN);
    Serial2.setTX(KNX_UART_TX_PIN);
  #endif
  #ifdef BOARD_MASIFI_MODBUS_V21
    Serial1.setRX(KNX_UART_RX_PIN);
    Serial1.setTX(KNX_UART_TX_PIN);
  #endif
#endif
    SERIAL_DEBUG.begin(115200);
    pinMode(get_PROG_LED_PIN(get_HW_ID()), OUTPUT);
    digitalWrite(get_PROG_LED_PIN(get_HW_ID()), HIGH);
    SERIAL_DEBUG.print("Startup delay: ");
    SERIAL_DEBUG.println(DEBUG_DELAY);
    delay(DEBUG_DELAY);
    digitalWrite(get_PROG_LED_PIN(get_HW_ID()), LOW);
#ifdef ARDUINO_ARCH_RP2040
  #ifdef BOARD_MASIFI_MODBUS_V21
    Serial2.setRX(MODBUS_UART_RX_PIN);
    Serial2.setTX(MODBUS_UART_TX_PIN);
  #endif
#endif
    SERIAL_DEBUG.println("Startup called...");
    ArduinoPlatform::SerialDebug = &SERIAL_DEBUG;

#ifdef INFO_LED_PIN
    pinMode(INFO_LED_PIN, OUTPUT);
    ledInfo(true);
#endif

    //I2C Init
    Wire.begin();
    Wire.setClock(400000);
    initHW(get_HW_ID());

    // pin or GPIO the programming led is connected to. Default is LED_BUILDIN
    knx.ledPin(get_PROG_LED_PIN(get_HW_ID()));
    // is the led active on HIGH or low? Default is LOW
    knx.ledPinActiveOn(get_PROG_LED_PIN_ACTIVE_ON(get_HW_ID()));
    // pin or GPIO programming button is connected to. Default is 0
    knx.buttonPin(get_PROG_BUTTON_PIN(get_HW_ID()));

  // all MAIN_* parameters are generated by OpenKNXproducer for correct version checking by ETS
  // If you want just a bugfix firmware update without ETS-Application dependency, just increase firmwareRevision.
  // As soon, as you want again a sync between ETS-Application and firmware, set firmwareRevision to 0.
  const uint8_t firmwareRevision = 0;
  OpenKNX::knxRead(MAIN_OpenKnxId, MAIN_ApplicationNumber, MAIN_ApplicationVersion, firmwareRevision);

  appSetup();

  // start the framework.
  knx.start();
  ledInfo(false);
}

void loop()
{
    // don't delay here to much. Otherwise you might lose packages or mess up the timing with ETS
    knx.loop();

    // only run the application code if the device was configured with ETS
    if (knx.configured())
    {
        appLoop();
    }
}
